name: UNIXBuildAndPublish

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  python-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release  --strip --interpreter python${{matrix.python_version}} --out dist

      - name: Install wheels
        run: pip install --no-index --find-links dist --force-reinstall

      -name: Upload wheels
       uses: actions/upload-artifact@v3
       with:
         name: wheels
         path: dist

  release:
    name: Release
    needs: [python-publish]
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifacts@v3
        with:
          name: wheels
      - name: Publish to PyPI
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI }}
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --skip-existing --usertname ${{ secrets.PYPY_USER}}

