name: WindowsBuildAndPublish

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  python-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build Python package
        run: poetry run maturin build --release --no-sdist --strip --interpreter python${{matrix.python_version}}

      - name: List wheels
        run: ls target/wheels/

      # Note: Windows doesn't support glob
      # https://stackoverflow.com/a/52481267/270334
      - name: Install wheels
        run: pip install --find-links=target/wheels trattoria_core

      - name: PyPi publish
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI }}
        run: poetry run maturin publish --username __token__ --interpreter python${{matrix.python_version}}

